### ISSUE TITLE
Override Browser Default Field Styles

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#3003]
Lots of browsers (e.g. Safari on iPad) add addtional default styles to field elements. 
![image39](https://user-images.githubusercontent.com/1088291/44668725-2866c580-a9ec-11e8-911b-01a52f08a89b.png)

We should audit and evaluate including some CSS overrides into the base field component, such that these addtional styles are overridden.

**Comment by towerofnix** [comment]
I have the same type of issue with Firefox on Linux, using the Arc Dark GTK theme:

![The same inputs as in carljbowman's screenshot, but with dark backgrounds and difficult to read text](https://user-images.githubusercontent.com/9948030/44728526-1b60d980-aab3-11e8-80dc-3792e0c0d069.png)

I ended up writing a generic userstyle to deal with this (since other sites also get their inputs messed up like that):

```css
input, textarea {
    background: white;
    color: #222;
}

input::placeholder {
    color: #999;
}
```
