### ISSUE TITLE
Language selector options are invisible until hovered over

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-gui#564]
### Expected Behavior

You should be able to see all the options for languages before choosing

### Actual Behavior

Instead, the background color AND the font color are both white - causing the options to be invisible until hovered over, when the background changes to blue.

### Steps to Reproduce

1. Open [scratch-gui](https://llk.github.io/scratch-gui/develop)
2. Click the language selector.
3. You can't see any options:
![image](https://user-images.githubusercontent.com/28599280/28553912-e2747a2e-7128-11e7-986e-ef9cf21e4f39.png)

### Probable cause
In one of the `style`s, we have:
```css
.language-selector_language-select_8Vfnm {
    width: 100%;
    height: 1.85rem;
    border: 1px solid #4c97ff;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    outline: none;
    background: rgba(255, 255, 255, 0.2);
    color: white;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
}
```
As you can see, `background` is white (well, RGBA white) and `color` is also white.
